name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    name: Test code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - ^1.15
          - ^1.16
          - ^1.17
          - ^1.22
          - ^1
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Build and run version
      run: |
        make VERSION=testing-version
        ./graphite-ch-optimizer --version
